version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: "@glimmer/syntax"
    versions:
    - 0.73.2
    - 0.74.0
    - 0.74.2
    - 0.75.0
    - 0.76.0
    - 0.77.1
    - 0.77.3
    - 0.77.4
    - 0.77.5
    - 0.77.6
    - 0.78.0
    - 0.78.2
  - dependency-name: html-entities
    versions:
    - 2.1.0
    - 2.1.1
    - 2.3.1
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
    - 2.0.1
  - dependency-name: postcss-import
    versions:
    - 14.0.0
  - dependency-name: ember-cli-mirage
    versions:
    - 2.0.1
